import { TestQuestion } from './types';

export const unit2Questions: TestQuestion[] = [
  {
    "id": "u2-01",
    "unit": 2,
    "topic": "Knowledge Representation",
    "subtopic": "Fuzzy Logic Defuzzification",
    "question": "Which module in a Fuzzy Logic System is responsible for transforming the fuzzy set outputs generated by the Inference Engine back into crisp numerical control values?",
    "options": [
      "Fuzzification Module",
      "Inference Engine",
      "Defuzzification Module",
      "Rule Base"
    ],
    "correctIndex": 2,
    "explanation": "Defuzzification is the process of mapping a fuzzy set membership function produced by the inference engine into a crisp, single numerical control value (e.g., using Centroid or Mean of Maxima).",
    "appearedIn": "Paper 5 (Q.I.A.i), Paper 1 (Q.I.B.iii), Paper 6 (Q.V.3)",
    "difficulty": "easy",
    "category": "mcq"
  },
  {
    "id": "u2-02",
    "unit": 2,
    "topic": "Knowledge Representation",
    "subtopic": "Fuzzification",
    "question": "The component in a Fuzzy Logic controller that converts crisp, real-world input sensor numbers into fuzzy linguistic truth values is termed as:",
    "options": [
      "Defuzzifier",
      "Fuzzification Module",
      "Normalizer",
      "Quantizer"
    ],
    "correctIndex": 1,
    "explanation": "Fuzzification converts crisp input values (e.g., Temperature = 38.5 C) into membership degrees across fuzzy linguistic sets (e.g., Warm: 0.7, Hot: 0.3).",
    "appearedIn": "Paper 1 (Q.I.B.iii)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-03",
    "unit": 2,
    "topic": "Logic & Reasoning",
    "subtopic": "Deductive Reasoning",
    "question": "Which form of reasoning begins with general premises/rules known to be true and applies them to specific cases to reach a guaranteed valid conclusion?",
    "options": [
      "Inductive Reasoning",
      "Abductive Reasoning",
      "Deductive Reasoning",
      "Analogical Reasoning"
    ],
    "correctIndex": 2,
    "explanation": "Deductive reasoning is truth-preserving: if the premises are true, the conclusion is guaranteed to be true (e.g., All humans are mortal; Socrates is human; Therefore Socrates is mortal).",
    "appearedIn": "Paper 5 (Q.5.c), Paper 6 (Q.V.5)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-04",
    "unit": 2,
    "topic": "Logic & Reasoning",
    "subtopic": "Abductive Reasoning",
    "question": "A doctor observes a patient with high fever and cough, and infers that the patient most likely has pneumonia. This process of forming the most plausible hypothesis from observed symptoms is:",
    "options": [
      "Deductive Reasoning",
      "Abductive Reasoning",
      "Inductive Reasoning",
      "Monotonic Reasoning"
    ],
    "correctIndex": 1,
    "explanation": "Abductive reasoning generates the best or most likely explanation from incomplete observations. Unlike deduction, the conclusion is plausible but not logically guaranteed.",
    "appearedIn": "Paper 6 (Q.III.5)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-05",
    "unit": 2,
    "topic": "Knowledge Representation",
    "subtopic": "Semantic Networks",
    "question": "In a Semantic Network representation of knowledge, what do the nodes and directed arcs (edges) represent?",
    "options": [
      "Nodes represent truth values; Arcs represent logical quantifiers",
      "Nodes represent concepts, objects, or situations; Arcs represent semantic relations (such as IS-A, PART-OF, HAS-A)",
      "Nodes represent neurons; Arcs represent synaptic weights",
      "Nodes represent probability distributions; Arcs represent random variables"
    ],
    "correctIndex": 1,
    "explanation": "Semantic Networks represent propositional knowledge as graph structures where vertices (nodes) represent objects or concepts, and directed edges (arcs) represent relationships like IS-A or HAS-A.",
    "appearedIn": "Paper 1 (Q.3.d)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-06",
    "unit": 2,
    "topic": "Knowledge Representation",
    "subtopic": "Frame Representation",
    "question": "Frame representation (proposed by Marvin Minsky) organizes knowledge into collections of attributes called ________ and corresponding values called ________.",
    "options": [
      "Keys and Hashes",
      "Slots and Fillers",
      "Rows and Columns",
      "Entities and Relations"
    ],
    "correctIndex": 1,
    "explanation": "A frame is a record-like structure consisting of named 'Slots' (attributes) and 'Fillers' (values or sub-frames). Frames support inheritance, default values, and procedural attachments (demons).",
    "appearedIn": "Paper 6 (Q.III.1)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-07",
    "unit": 2,
    "topic": "Knowledge Representation",
    "subtopic": "Types of Knowledge",
    "question": "Knowledge that expresses rules of thumb, educated guesses, and rules derived from expert experience rather than mathematical deduction is termed as:",
    "options": [
      "Declarative Knowledge",
      "Procedural Knowledge",
      "Meta-knowledge",
      "Heuristic Knowledge"
    ],
    "correctIndex": 3,
    "explanation": "Heuristic knowledge represents rules of thumb, experience-based insights, and plausible rules that help solve complex problems efficiently even when complete algorithms are lacking.",
    "appearedIn": "Paper 5 (Q.3.e)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-08",
    "unit": 2,
    "topic": "Logic & Reasoning",
    "subtopic": "Propositional Logic",
    "question": "In Propositional Logic, a compound formula that evaluates to TRUE under every possible truth assignment of its propositional variables is called a:",
    "options": [
      "Contradiction",
      "Tautology (Valid sentence)",
      "Contingency",
      "Horn Clause"
    ],
    "correctIndex": 1,
    "explanation": "A sentence is valid (or a Tautology) if it is true in all possible models under all truth interpretations (e.g. P v not P). If it is false in all models, it is a Contradiction/Unsatisfiable.",
    "appearedIn": "Paper 7 (Q.3.b-OR), Paper 8 (Q.III.e)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-09",
    "unit": 2,
    "topic": "Ensemble Learning",
    "subtopic": "AdaBoost Algorithm",
    "question": "In the AdaBoost algorithm, for a sufficiently large number of boosting iterations K, the final ensemble hypothesis classifies the ________ perfectly (assuming base learners are better than random guessing).",
    "options": [
      "Training data",
      "Testing data",
      "Unseen validation data",
      "Hyperparameter grid"
    ],
    "correctIndex": 0,
    "explanation": "AdaBoost iteratively increases the weights of misclassified examples. Freund & Schapire proved that AdaBoost drives the training error down to zero exponentially fast as K grows.",
    "appearedIn": "Paper 1 (Q.I.A.i)",
    "difficulty": "medium",
    "category": "mcq"
  },
  {
    "id": "u2-10",
    "unit": 2,
    "topic": "Machine Learning Models",
    "subtopic": "Nonparametric Models",
    "question": "A learning model whose complexity and number of parameters can grow flexibly with the size of the training dataset (i.e. cannot be characterized by a fixed bounded set of parameters) is called a:",
    "options": [
      "Parametric model",
      "Nonparametric model",
      "Linear regression model",
      "Logistic regression model"
    ],
    "correctIndex": 1,
    "explanation": "Parametric models (like Linear Regression) summarize data with a fixed number of parameters. Nonparametric models (like K-NN, Decision Trees, or SVM with RBF kernel) allow parameter count and capacity to grow with data size.",
    "appearedIn": "Paper 4 (Q.I.A.iv), Paper 6 (Q.I.A.4), Paper 1 (Q.3.f)",
    "difficulty": "medium",
    "category": "mcq"
  },
  {
    "id": "u2-11",
    "unit": 2,
    "topic": "Ensemble Learning",
    "subtopic": "Boosting vs Bagging",
    "question": "Which of the following is the most widely used sequential ensemble method in machine learning?",
    "options": [
      "Boosting",
      "Hashing",
      "Stacking",
      "K-Means"
    ],
    "correctIndex": 0,
    "explanation": "Boosting (such as AdaBoost, Gradient Boosting, XGBoost) is the most prominent ensemble technique where weak learners are trained sequentially, each focusing on mistakes made by earlier models.",
    "appearedIn": "Paper 5 (Q.I.A.iv), Paper 6 (Q.I.A.5)",
    "difficulty": "easy",
    "category": "mcq"
  },
  {
    "id": "u2-12",
    "unit": 2,
    "topic": "Supervised Learning",
    "subtopic": "Supervised vs Unsupervised",
    "question": "Which of the following algorithms is NOT a supervised learning algorithm?",
    "options": [
      "Principal Component Analysis (PCA)",
      "Decision Tree Classifier",
      "Linear Regression",
      "Naive Bayes Classifier"
    ],
    "correctIndex": 0,
    "explanation": "PCA (Principal Component Analysis) is an unsupervised dimensionality reduction technique that finds directions of maximum variance without using output labels.",
    "appearedIn": "Paper 7 (Q.I.A.6), Paper 8 (Q.IA.vi)",
    "difficulty": "easy",
    "category": "mcq"
  },
  {
    "id": "u2-13",
    "unit": 2,
    "topic": "Regression Models",
    "subtopic": "Python Scikit-Learn",
    "question": "In Python's scikit-learn library (sklearn.linear_model), which class is instantiated to perform standard ordinary least squares linear regression?",
    "options": [
      "LinearRegression()",
      "OLS_Model()",
      "LinearRegressor()",
      "LeastSquares()"
    ],
    "correctIndex": 0,
    "explanation": "LinearRegression() from sklearn.linear_model fits a linear model with coefficients w = (w1, ..., wp) to minimize the residual sum of squares between observed and predicted targets.",
    "appearedIn": "Paper 2 (Q.1.B.2), Paper 3 (Q.I.B.b)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-14",
    "unit": 2,
    "topic": "Regression Models",
    "subtopic": "Multiple Linear Regression",
    "question": "When a linear regression model predicts a continuous target variable y using two or more independent input features (x1, x2, ..., xn), it is termed as:",
    "options": [
      "Simple Linear Regression",
      "Multiple Linear Regression",
      "Logistic Regression",
      "Polynomial Clustering"
    ],
    "correctIndex": 1,
    "explanation": "Multiple Linear Regression models the relationship between two or more independent explanatory variables and a single continuous dependent variable: y = b0 + b1*x1 + b2*x2 + ... + bn*xn.",
    "appearedIn": "Paper 2 (Q.1.B.3), Paper 3 (Q.I.B.c)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-15",
    "unit": 2,
    "topic": "Neural Networks",
    "subtopic": "Backpropagation",
    "question": "The foundational algorithm used in Artificial Neural Networks to compute gradients and adjust synaptic weights by propagating errors backward from the output layer to hidden layers is:",
    "options": [
      "Backpropagation",
      "Forward Selection",
      "Perceptron Halting",
      "Defuzzification"
    ],
    "correctIndex": 0,
    "explanation": "Backpropagation (backward propagation of errors) uses the mathematical chain rule of calculus to calculate the gradient of the loss function with respect to each weight, allowing gradient descent optimization.",
    "appearedIn": "Paper 2 (Q.1.B.4), Paper 3 (Q.I.B.d), Paper 5 (Q.3.a)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-16",
    "unit": 2,
    "topic": "Decision Trees",
    "subtopic": "Attribute Selection Criteria",
    "question": "Decision Tree learning algorithms (such as ID3 and C4.5) use which primary quantitative criterion to choose the best splitting attribute at each node?",
    "options": [
      "Information Gain (or Entropy Reduction / Gini Index)",
      "Euclidean Distance",
      "Gradient Descent Learning Rate",
      "Kernel Gram Matrix"
    ],
    "correctIndex": 0,
    "explanation": "Decision trees choose the attribute that provides the highest Information Gain (greatest reduction in Shannon Entropy) or lowest Gini Impurity to construct pure sub-nodes.",
    "appearedIn": "Paper 7 (Q.I.B.6), Paper 8 (Q.I.B.f)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-17",
    "unit": 2,
    "topic": "Machine Learning Foundations",
    "subtopic": "Overfitting",
    "question": "What is 'Overfitting' in machine learning?",
    "options": [
      "When a model performs poorly on both training and test data due to excessive simplicity",
      "When a model fits training data too closely, learning random noise instead of general underlying patterns, resulting in poor generalization on unseen test data",
      "When the model's weights remain initialized at zero",
      "When the dataset contains missing values"
    ],
    "correctIndex": 1,
    "explanation": "Overfitting occurs when a complex hypothesis fits the training data too tightly (high variance, low bias). It captures idiosyncrasies and noise of the training set, causing test accuracy to degrade.",
    "appearedIn": "Paper 1 (Q.I.c.iv)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-18",
    "unit": 2,
    "topic": "Machine Learning Foundations",
    "subtopic": "Definition of Supervised Learning",
    "question": "Supervised Learning is best described as a paradigm where:",
    "options": [
      "The model discovers hidden cluster structures without any target output labels",
      "The model receives feedback in the form of environmental penalties and rewards",
      "The model is provided with labeled training data consisting of paired inputs and desired target outputs to learn an approximating function",
      "The model generates synthetic data autonomously without human supervision"
    ],
    "correctIndex": 2,
    "explanation": "In supervised learning, the agent is given an example set of input-output pairs (x1, y1), (x2, y2), ... and learns a function f that maps new inputs x to accurate predictions y.",
    "appearedIn": "Paper 6 (Q.I.C.3), Paper 7 (Q.V.a-OR)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-19",
    "unit": 2,
    "topic": "Machine Learning Models",
    "subtopic": "Nonparametric Examples",
    "question": "Which of the following is a classic example of a Nonparametric machine learning algorithm?",
    "options": [
      "K-Nearest Neighbors (K-NN)",
      "Ordinary Least Squares Linear Regression",
      "Logistic Regression",
      "Gaussian Naive Bayes"
    ],
    "correctIndex": 0,
    "explanation": "K-Nearest Neighbors (K-NN) is a purely nonparametric instance-based learner. It stores all training instances and makes no prior assumptions about the functional form of the data distribution.",
    "appearedIn": "Paper 6 (Q.I.C.2), Paper 1 (Q.3.f)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-20",
    "unit": 2,
    "topic": "Classification Models",
    "subtopic": "Logistic Regression",
    "question": "In Logistic Regression for binary classification, which mathematical function is used to map real-valued linear outputs into probabilities bounded between 0 and 1?",
    "options": [
      "Sigmoid (Logistic) Function: 1 / (1 + e^-z)",
      "Softplus Function",
      "Linear Identity Function",
      "Rectified Linear Unit (ReLU)"
    ],
    "correctIndex": 0,
    "explanation": "The Sigmoid activation function maps any real number z = w^T x + b into a valid probability in the range (0, 1), defined as sigma(z) = 1 / (1 + e^(-z)).",
    "appearedIn": "Paper 1 (Q.3.a), Paper 6 (Q.III.3), Paper 7 (Q.3.b)",
    "difficulty": "easy",
    "category": "concept",
    "formula": "sigma(z) = 1 / (1 + e^-z)"
  },
  {
    "id": "u2-21",
    "unit": 2,
    "topic": "Regularization Techniques",
    "subtopic": "L1 vs L2 Regularization",
    "question": "What is the crucial practical difference between L1 Regularization (LASSO) and L2 Regularization (Ridge Regression)?",
    "options": [
      "L1 adds a squared penalty; L2 adds an absolute penalty",
      "L1 (LASSO) drives uninformative feature weights strictly to zero, effectively performing feature selection and producing sparse models; L2 (Ridge) shrinks weights toward zero without setting them exactly to zero",
      "L1 is used only for classification, while L2 is used only for clustering",
      "L1 regularization always causes severe underfitting"
    ],
    "correctIndex": 1,
    "explanation": "L1 (Lasso) uses the L1-norm penalty lambda * sum(|w_j|). Its diamond-shaped constraint boundary forces weights of redundant features to exactly 0, creating sparsity. L2 (Ridge) uses lambda * sum(w_j^2), shrinking weights evenly without eliminating features.",
    "appearedIn": "Paper 1 (Q.3.e), Paper 6 (Q.III.2), Paper 6 (Q.V.3)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-22",
    "diagram": "svm-margin",
    "unit": 2,
    "topic": "Support Vector Machines",
    "subtopic": "Support Vectors & Margin",
    "question": "In Support Vector Machines (SVM), what are 'Support Vectors'?",
    "options": [
      "The training data points that lie closest to the decision boundary (hyperplane) and directly determine the orientation and margin of the hyperplane",
      "The eigenvectors of the covariance matrix",
      "The misclassified points discarded as outliers",
      "The random weights assigned to hidden layer neurons"
    ],
    "correctIndex": 0,
    "explanation": "Support vectors are the critical data points lying right on the margins. Removing non-support vector data points does not change the optimal hyperplane at all; only the support vectors define the boundary.",
    "appearedIn": "Paper 1 (Q.3.c), Paper 4 (Q.III.d), Paper 7 (Q.3.a)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-23",
    "unit": 2,
    "topic": "Support Vector Machines",
    "subtopic": "Kernel Trick",
    "question": "Why is the 'Kernel Trick' utilized in Support Vector Machines?",
    "options": [
      "To speed up hard drive reads during training",
      "To map linearly non-separable input data into a higher-dimensional feature space where it becomes linearly separable, without explicitly computing coordinates in that high-dimensional space",
      "To replace quadratic programming with simple sorting",
      "To convert continuous regression labels into discrete classes"
    ],
    "correctIndex": 1,
    "explanation": "The Kernel Trick computes dot products in a high-dimensional feature space directly using kernel functions (like Polynomial or RBF) without ever explicitly mapping data points into that complex space.",
    "appearedIn": "Paper 2 (Q.3.e-OR), Paper 8 (Q.III.a)",
    "difficulty": "hard",
    "category": "concept"
  },
  {
    "id": "u2-24",
    "unit": 2,
    "topic": "Neural Networks",
    "subtopic": "Perceptron Limitation",
    "question": "What famous limitation of the Single-Layer Perceptron was mathematically demonstrated by Minsky and Papert in 1969?",
    "options": [
      "A single-layer perceptron cannot learn the boolean AND function",
      "A single-layer perceptron can only classify linearly separable functions and cannot learn non-linear functions like the XOR (Exclusive OR) problem",
      "Perceptrons cannot use gradient descent",
      "Perceptrons cannot be trained with more than 2 inputs"
    ],
    "correctIndex": 1,
    "explanation": "Single-layer perceptrons have linear decision boundaries. Since the XOR function is not linearly separable, a single-layer perceptron cannot solve it. This necessitated Multi-Layer Perceptrons (MLPs).",
    "appearedIn": "Paper 4 (Q.V.c), Paper 6 (Q.V.1)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-25",
    "diagram": "neuron-model",
    "unit": 2,
    "topic": "Neural Networks",
    "subtopic": "Mathematical Model of Neuron",
    "question": "In the mathematical model of an artificial neuron, if inputs are x1, x2 with weights w1=0.5, w2=0.8, bias b = -0.4, what is the net input z before applying the activation function when x1=2, x2=1?",
    "options": [
      "1.4",
      "1.8",
      "2.2",
      "0.9"
    ],
    "correctIndex": 0,
    "explanation": "Net input z = w1*x1 + w2*x2 + b = (0.5 * 2) + (0.8 * 1) + (-0.4) = 1.0 + 0.8 - 0.4 = 1.4.",
    "appearedIn": "Paper 1 (Q.3.b), Paper 7 (Q.3.c)",
    "difficulty": "medium",
    "category": "numerical",
    "formula": "z = sum(w_i * x_i) + b"
  },
  {
    "id": "u2-26",
    "unit": 2,
    "topic": "Decision Trees",
    "subtopic": "Entropy Calculation",
    "question": "A training dataset S has 4 positive examples and 4 negative examples (p+ = 0.5, p- = 0.5). What is the Shannon Entropy H(S)?",
    "options": [
      "0.0 bits",
      "0.5 bits",
      "1.0 bit",
      "2.0 bits"
    ],
    "correctIndex": 2,
    "explanation": "H(S) = - p+ * log2(p+) - p- * log2(p-) = - 0.5 * log2(0.5) - 0.5 * log2(0.5) = - 0.5 * (-1) - 0.5 * (-1) = 0.5 + 0.5 = 1.0 bit. Maximum uncertainty equals 1 bit.",
    "appearedIn": "Paper 2 (Q.3.a-OR), Paper 4 (Q.III.b)",
    "difficulty": "medium",
    "category": "numerical",
    "formula": "H(S) = - sum(p_i * log2(p_i))"
  },
  {
    "id": "u2-27",
    "unit": 2,
    "topic": "Decision Trees",
    "subtopic": "Zero Entropy",
    "question": "Under what condition is the Shannon Entropy H(S) of a sample set S exactly equal to 0?",
    "options": [
      "When the sample contains an equal number of positive and negative classes",
      "When all instances in S belong to the exact same class (completely homogeneous)",
      "When there are no features in the dataset",
      "When the tree reaches a depth of 10"
    ],
    "correctIndex": 1,
    "explanation": "If all members of S belong to the same class (e.g. 10 positive, 0 negative), there is no uncertainty: H(S) = - 1.0 * log2(1.0) - 0 = 0 bits.",
    "appearedIn": "Paper 4 (Q.III.b), Paper 8 (Q.III.d)",
    "difficulty": "easy",
    "category": "concept"
  },
  {
    "id": "u2-28",
    "unit": 2,
    "topic": "Instance-Based Learning",
    "subtopic": "K-Nearest Neighbors",
    "question": "Why is K-Nearest Neighbors (K-NN) referred to as a 'Lazy Learner' (Instance-Based Learner)?",
    "options": [
      "Because it does not execute on GPUs",
      "Because it defers all computation and generalization until a query instance needs to be classified at runtime, building no explicit global model during training",
      "Because it only works when k=1",
      "Because it uses an excessively small learning rate"
    ],
    "correctIndex": 1,
    "explanation": "K-NN simply stores the training instances ('lazy learning'). It builds no explicit training model; when an unseen test sample arrives, it computes distances to all stored points on demand.",
    "appearedIn": "Paper 5 (Q.3.f), Paper 6 (Q.V.6), Paper 7 (Q.3.c-OR)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-29",
    "unit": 2,
    "topic": "Instance-Based Learning",
    "subtopic": "K-NN Distance Metric",
    "question": "Given two 2D points P1 = (2, 3) and P2 = (5, 7), what is the Euclidean Distance between them used in K-NN?",
    "options": [
      "7",
      "5",
      "12",
      "25"
    ],
    "correctIndex": 1,
    "explanation": "Euclidean Distance = sqrt((x2 - x1)^2 + (y2 - y1)^2) = sqrt((5 - 2)^2 + (7 - 3)^2) = sqrt(3^2 + 4^2) = sqrt(9 + 16) = sqrt(25) = 5.",
    "appearedIn": "Paper 5 (Q.3.f)",
    "difficulty": "medium",
    "category": "numerical",
    "formula": "d = sqrt((x2-x1)^2 + (y2-y1)^2)"
  },
  {
    "id": "u2-30",
    "unit": 2,
    "topic": "Ensemble Learning",
    "subtopic": "Bagging vs Random Forest",
    "question": "How does Random Forest improve upon standard Bagging of Decision Trees?",
    "options": [
      "By pruning every tree down to a single decision stump",
      "By introducing feature randomness: selecting a random subset of candidate features at each split, which decorrelates the trees and reduces ensemble variance",
      "By training trees sequentially on the residuals of previous trees",
      "By replacing decision trees with perceptrons"
    ],
    "correctIndex": 1,
    "explanation": "Random Forest builds bagged trees with randomized feature subsets at each split. This decorrelates the individual trees so that strong features don't dominate every tree, substantially reducing variance.",
    "appearedIn": "Paper 2 (Q.3.c), Paper 4 (Q.III.f)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-31",
    "diagram": "decision-tree",
    "unit": 2,
    "topic": "Decision Trees",
    "subtopic": "Restaurant Waiting Problem",
    "question": "In the classic Restaurant Waiting Problem from Russell & Norvig, which attribute is typically found to have the highest Information Gain at the root of the decision tree?",
    "options": [
      "Patrons (None, Some, Full)",
      "Price ($, $$, $$$)",
      "Rain (Yes, No)",
      "Reservation (Yes, No)"
    ],
    "correctIndex": 0,
    "explanation": "Patrons is the most informative attribute: if Patrons=None, wait is None; if Patrons=Some, wait is short; if Patrons=Full, further tests are needed. It yields the highest information gain at the root.",
    "appearedIn": "Paper 2 (Q.3.a-OR), Paper 6 (Q.V.3)",
    "difficulty": "medium",
    "category": "concept"
  },
  {
    "id": "u2-32",
    "unit": 2,
    "topic": "Machine Learning Foundations",
    "subtopic": "Bias-Variance Tradeoff",
    "question": "A model that is overly simplistic (such as fitting a straight line to highly curved cubic data) suffers from:",
    "options": [
      "High Bias (Underfitting)",
      "High Variance (Overfitting)",
      "Zero Training Error",
      "Nonparametric Instability"
    ],
    "correctIndex": 0,
    "explanation": "High bias occurs when the model makes strong, erroneous assumptions about the data (underfitting). High variance occurs when the model is overly sensitive to fluctuations in training data (overfitting).",
    "appearedIn": "Paper 1 (Q.3.e), Paper 1 (Q.3.f)",
    "difficulty": "easy",
    "category": "concept"
  }
];
